### ISSUE TITLE
Confusion on `body` vs `params` arguments

### ISSUE THREAD

**Issue by swanson** [HealthTechDevelopers/athena_health#45]
When calling `AthenaHealth::Endpoints::Appointments#cancel_appointment` the method signature accepts a `body:` argument. 

Other endpoints (like `AthenaHealth::Endpoints::Appointments#book_appointment`) only accept a `params:` argument. 

Both endpoints are using the `PUT` verb.

Is there a reason that both `params` and `body` are used for `PUT` calls? I found this be surprising when working with the API; I would expect `body` to be used for any non-`GET` endpoints.

**Comment by MatUrbanski** [comment]
According to the `AthenaHealth:: Endpoints::Appointments#book_appointment` it is done this way because Athena expects to have `patientid` parameter in url. Url for booking appointment needs to look like this: `https://api.athenahealth.com/preview1/195900/appointments/659324?appointmenttypeid=82&patientid=1`

**Comment by swanson** [comment]
Thanks, sounds like an issue I'd need to take up with Athena API team.
